### ISSUE TITLE
horizontal scroll not working<eom>

### ISSUE THREAD

**Issue by sourabhkejriwal** [terwanerik/ScrollTrigger#46] opened 2018-07-01 07:30 UTC

**Comment by terwanerik** [comment] 2018-09-22 08:39
Could you give an explanation / provide an example? What device etc?

**Comment by terwanerik** [comment] 2018-09-22 08:40
Might be a duplicate of #16

**Comment by terwanerik** [comment] 2019-11-12 15:28
v1.0 is just released! Could you check if this issue still exists? Please note that the API has changed quite a bit.

**Closed by terwanerik** 2019-11-12 15:28 UTC
