### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by MikeHarrison** [terwanerik/ScrollTrigger#8] opened 2016-07-05 14:05 UTC
Hi,

Your demo page is working great, but my implementation of ScrollTrigger is not working on iOS. I am trying to track down the issue now. I am calling jQuery before it, which I think may be a factor. The initial `invisible` class is being applied, but not the `visible`

**Comment by terwanerik** [comment] 2016-07-05 14:46
Hm sounds strange, could you create a [http://stackoverflow.com/help/mcve](minimal, complete and verifiable example)? And upload that to codepen.io or something like that? Cannot reproduce this bug.

**Comment by MikeHarrison** [comment] 2016-07-05 14:58
Here is a codepen, where I am seeing the same issue:

http://codepen.io/mikehdesign/pen/qNjJEj

**Comment by terwanerik** [comment] 2016-07-05 15:36
Thanks! I'm looking into it.

**Comment by terwanerik** [comment] 2016-07-05 15:52
Now fixed in v0.2.4 and v0.1.3

**Closed by terwanerik** 2016-07-05 15:52 UTC

**Comment by MikeHarrison** [comment] 2016-07-05 16:00
Great - thanks for the quick work!
